' """
FILE: curl.bas

This is the BASIC import file for the module curl.

This file was generated by headerer.pl from the file 
Do not edit this file, rather edit the file  and use
headerer.pl to regenerate this file.
"""

module curl

' FUNCTION DECLARATIONS 
declare sub     ::init     alias "sb_curl_init"     lib "curl"
declare sub     ::option   alias "sb_curl_option"   lib "curl"
declare sub     ::perform  alias "sb_curl_perform"  lib "curl"
declare sub     ::info     alias "sb_curl_info"     lib "curl"
declare sub     ::finish   alias "sb_curl_finish"   lib "curl"
declare sub     ::error    alias "sb_curl_error"    lib "curl"
declare sub     ::escape   alias "sb_curl_escape"   lib "curl"
declare sub     ::unescape alias "sb_curl_unescape" lib "curl"
declare sub     ::getdate  alias "sb_curl_getdate"  lib "curl"
declare sub     ::version  alias "sb_curl_version"  lib "curl"

end module
