' """
FILE: odbc.bas

This is the BASIC import file for the module odbc.

This file was generated by headerer.pl from the file 
Do not edit this file, rather edit the file  and use
headerer.pl to regenerate this file.
"""

module odbc

' FUNCTION DECLARATIONS 
declare sub     ::FetchArray   alias "odbc_fetcharray"     lib "odbc"
declare sub     ::FetchHash    alias "odbc_fetchhash"      lib "odbc"
declare sub     ::AffectedRows alias "odbc_affected_rows"  lib "odbc"
declare sub     ::Error        alias "odbc_error"          lib "odbc"
declare sub     ::Query        alias "odbc_query"          lib "odbc"
declare sub     ::Close        alias "odbc_close"          lib "odbc"
declare sub     ::RealConnect  alias "odbc_real_connect"   lib "odbc"
declare sub     ::Connect      alias "odbc_config_connect" lib "odbc"

end module
