' """
FILE: sqlite.bas

This is the BASIC import file for the module sqlite.

This file was generated by headerer.pl from the file interface.c
Do not edit this file, rather edit the file interface.c and use
headerer.pl to regenerate this file.
"""

module sqlite

SQLITE3_OK          =   0
SQLITE3_ERROR       =   1
SQLITE3_INTERNAL    =   2
SQLITE3_PERM        =   3
SQLITE3_ABORT       =   4
SQLITE3_BUSY        =   5
SQLITE3_LOCKED      =   6
SQLITE3_NOMEM       =   7
SQLITE3_READONLY    =   8
SQLITE3_INTERRUPT   =   9
SQLITE3_IOERR       =  10
SQLITE3_CORRUPT     =  11
SQLITE3_NOTFOUND    =  12  
SQLITE3_FULL        =  13
SQLITE3_CANTOPEN    =  14  
SQLITE3_PROTOCOL    =  15  
SQLITE3_EMPTY       =  16  
SQLITE3_SCHEMA      =  17
SQLITE3_TOOBIG      =  18
SQLITE3_CONStraint  =  19
SQLITE3_MISMATCH    =  20
SQLITE3_MISUSE      =  21
SQLITE3_NOLFS       =  22
SQLITE3_AUTH        =  23
SQLITE3_ROW         = 100
SQLITE3_DONE        = 101

SQLITE3_STATIC      =   0
SQLITE_TRANSIENT    =  -1

SQLITE_INTEGER      =   1
SQLITE_FLOAT        =   2
SQLITE_TEXT         =   3
SQLITE_BLOB         =   4
SQLITE_NULL         =   5
    
' FUNCTION DECLARATIONS 
declare sub     ::OPEN         alias "sql3_open"         lib "sqlite"
declare sub     ::CLOSE        alias "sql3_close"        lib "sqlite"
declare sub     ::EXECUTE      alias "sql3_execute"      lib "sqlite"
declare sub     ::QUERY        alias "sql3_query"        lib "sqlite"
declare sub     ::ROW          alias "sql3_row"          lib "sqlite"
declare sub     ::ROW_VALUE    alias "sql3_row_value"    lib "sqlite"
declare sub     ::COLUMN_COUNT alias "sql3_column_count" lib "sqlite"
declare sub     ::COLUMN_NAME  alias "sql3_column_name"  lib "sqlite"
declare sub     ::FINALIZE     alias "sql3_finalize"     lib "sqlite"
declare sub     ::VERSION      alias "sql3_version"      lib "sqlite"
declare sub     ::ErrorCode    alias "sql3_errorcode"    lib "sqlite"
declare sub     ::ErrorMsg     alias "sql3_errormsg"     lib "sqlite"
declare sub     ::FETCHHASH    alias "sql3_fetchhash"    lib "sqlite"
declare sub     ::FETCHARRAY   alias "sql3_fetcharray"   lib "sqlite"

end module
