' """
FILE: t.bas

This is the BASIC import file for the module t.

This file was generated by headerer.pl from the file tools.c
Do not edit this file, rather edit the file tools.c and use
headerer.pl to regenerate this file.
"""

module t

' FUNCTION DECLARATIONS 
declare sub     ::StringToArray    alias "unserialize"    lib "t"
declare sub     ::savestring       alias "savestring"     lib "t"
declare sub     ::loadstring       alias "loadstring"     lib "t"
declare sub     ::MD5              alias "md5fun"         lib "t"
declare sub     ::StringToArrayMD5 alias "md5unserialize" lib "t"
declare sub     ::Exit             alias "toolExit"       lib "t"

' COMMAND DECLARATIONS 
declare command ::ArrayToString    alias "serialize"      lib "t"
declare command ::ArrayToXML       alias "xmlserialize"   lib "t"
declare command ::ArrayToStringMD5 alias "md5serialize"   lib "t"

end module
