' """
FILE: trial.bas

This is the BASIC import file for the module trial.

This file was generated by headerer.pl from the file 
Do not edit this file, rather edit the file  and use
headerer.pl to regenerate this file.
"""

module trial

' FUNCTION DECLARATIONS 
declare sub     ::pprint  alias "pprint"  lib "trial"
declare sub     ::set1    alias "set1"    lib "trial"
declare sub     ::arbdata alias "arbdata" lib "trial"
declare sub     ::pzchar  alias "pzchar"  lib "trial"
declare sub     ::trial   alias "trial"   lib "trial"
declare sub     ::myicall alias "myicall" lib "trial"

' COMMAND DECLARATIONS 
declare command ::iff     alias "iff"     lib "trial"

end module
