' """
FILE: ux.bas

This is the BASIC import file for the module ux.

This file was generated by headerer.pl from the file 
Do not edit this file, rather edit the file  and use
headerer.pl to regenerate this file.
"""

module ux

' FUNCTION DECLARATIONS 
declare sub     ::fork  alias "uxfork"  lib "ux"
declare sub     ::chmod alias "uxchmod" lib "ux"

end module
