' """
FILE: zlib.bas

This is the BASIC import file for the module zlib.

This file was generated by headerer.pl from the file 
Do not edit this file, rather edit the file  and use
headerer.pl to regenerate this file.
"""

module zlib

' FUNCTION DECLARATIONS 
declare sub     ::compress   alias "zlbcmprs" lib "zlib"
declare sub     ::uncompress alias "zlbucprs" lib "zlib"
declare sub     ::gzip       alias "gzipfunc" lib "zlib"
declare sub     ::gunzip     alias "gunzpfnc" lib "zlib"

end module
